server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka/

zuul:
  routes:
    osinfo:
      path: /osinfo/**
      serviceId: OSINFO
    jinfo:
      path: /jinfo/**
      serviceId: JINFO
    
spring:
  application:
    name: zuul

management:
  security:
    enabled: false