server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka/

zuul:
  prefix: /api
Eureka:
  routes:
    osinfo:
      path: /osinfo
      serviceId: OSINFO
    jinfo:
      path: /jinfo
      serviceId: JINFO
    
spring:
  application:
    name: zuul