server:
   port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka/

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    osinfo:
      path: /osinfo/**
      serviceId: OSINFO
      stripPrefix: false
      sensitiveHeaders: Authorization
    jinfo:
      path: /jinfo/**
      serviceId: JINFO
      stripPrefix: false
      sensitiveHeaders: Authorization

spring:
  application:
    name: zuul

management:
  security:
    enabled: false